# Generated by Django 3.0.8 on 2021-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=250)),
                ('Location', models.CharField(max_length=250)),
                ('Client_Name', models.CharField(max_length=250)),
                ('Functional_Area', models.CharField(max_length=250)),
                ('Industry', models.CharField(max_length=250)),
                ('Experience', models.CharField(max_length=250)),
                ('Job_Description', models.TextField()),
                ('Rate_Card', models.CharField(max_length=250)),
                ('Salary_LPA', models.CharField(max_length=250)),
                ('Notice_Period', models.CharField(max_length=250)),
                ('Posted_On', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
