# Generated by Django 3.0.8 on 2021-11-08 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_upload',
            name='Posted_On',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
