# Generated by Django 3.0.8 on 2021-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0002_auto_20211108_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='Education',
            field=models.CharField(default='UG/PG', max_length=250),
        ),
    ]
