# Generated by Django 3.0.8 on 2021-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0003_job_upload_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='Openings',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Role',
            field=models.CharField(default='', max_length=250),
        ),
    ]
