# Generated by Django 3.0.8 on 2021-11-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0004_auto_20211115_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='Job_Description1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Description2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Description3',
            field=models.TextField(default=''),
        ),
    ]
