# Generated by Django 3.0.8 on 2021-12-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0005_auto_20211115_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='Freelancing',
            field=models.CharField(default='No', max_length=250),
        ),
    ]
