# Generated by Django 3.0.8 on 2021-12-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0008_auto_20211220_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_upload',
            name='About_Company_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='About_Company_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='About_Company_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Skills_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Skills_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Skills_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Job_Skills_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Offer_Type',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Required_Skills_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Required_Skills_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Required_Skills_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Required_Skills_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job_upload',
            name='Skill_Set',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
